### ISSUE TITLE
[s3sync] ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by claflico** [vladgh/docker_base_images#98]
```
docker run -e AWS_ACCESS_KEY_ID=OUR_ACCESS_KEY -e AWS_SECRET_ACCESS_KEY=OUR_SECRET_KEY -e AWS_DEFAULT_REGION=us-west-1 -e S3PATH=s3://OUR_BUCKET/d0 vladgh/s3sync
[2020-07-24T06:07:06+0000 - 1daf22172bb9] Sync 's3://OUR_BUCKET/d0' to '/sync'
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3.8/site-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/lib/python3.8/site-packages/botocore/session.py", line 28, in <module>
    import botocore.configloader
  File "/usr/lib/python3.8/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/usr/lib/python3.8/site-packages/botocore/compat.py", line 26, in <module>
    from dateutil.tz import tzlocal
  File "/usr/lib/python3.8/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/usr/lib/python3.8/site-packages/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by claflico** [comment]
aws-cli is available in the alpine repo now. 

Fixed by adding aws-cli:

`RUN apk --no-cache add aws-cli bash findutils groff less python3 tini inotify-tools`

was able to remove the "Install AWS CLI" section

**Comment by vladgh** [comment]
Thanks, I will update the docker image to use the packaged version of aws cli.

**Comment by claflico** [comment]
Tested and confirmed working. Thank you!
